### PR TITLE
v4 DB upgrade fix

### PR DESCRIPTION
**Pull request by BWibo**
I tried upgrading some of my DB's using `psql -h theHost-U postgres -d theDB -f UPGRADE_DB.sql` from `v4.0.3` to `v4.1.0`. 

I was getting this and no upgrade was done.

```text
Upgrading 3DCityDB ...

Checking version of the 3DCityDB instance ...
4.0.3
DO_NOTHING.sql

The 3DCityDB is already up to date. No action required.

3DCityDB upgrade complete!
```

This happens because the version info in `UPGRADE_DB.sql` appears to be outdated.
This PR fixes this.

### CODE REVIEW

**Comment by clausnagel** [comment]
Good catch, thanks @BWibo.

**Comment by yaozhihang** [comment]
Thanks @BWibo Would you like to also check and fix the Oracle version?

**Comment by BWibo** [comment]
I added the fix, but i wasn't able to test this, probably due to lack of experience with Oracle.

I build an Oracle image with 3DCityDB ``v4.0.3`` and run it like this:

```bash
docker run --name 3dcitydb -p 1521:1521 -i -t \
     -e ORACLE_USER=user \
     -e ORACLE_PASSDWORD=test \
     -e SRID=25832 \
   3dcitydb/3dcitydb-ora:4.0.3
`` 
I connect using:

```bash
docker run --net host -i -t --rm -v ${PWD/mnt\/}:/share \ 
  container-registry.oracle.com/database/instantclient sqlplus \
  PDBADMIN/thePassword@//localhost:1521/ORCLPDB1 @/share/UPGRADE_DB.sql
```
After that I am asked this: 
```
SQL*Plus: Release 12.2.0.1.0 Production on Thu May 20 08:22:40 2021

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Last Successful login time: Thu May 20 2021 08:20:57 +00:00

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

Enter value for 1: 
```

What is 1? Is this documented anywhere? I also didn't manage to get a connection with Importer/Exporter.
@yaozhihang Can you give me an example of the connection parameters I have to use with Importer/Exporter?

One more thing: Is it normal that the database take ~10 minutes to become available when launching a new container?

**Comment by yaozhihang** [comment]
@BWibo thanks for the fix. You may try using the `ORACLE_USER` value (in your example it is  `user`) instead of `PDBADMIN`. Yes, it takes also a few miniutes on my computer for lanching a new container.

**Comment by BWibo** [comment]
@yaozhihang 
Hey there, I tried lots of things but I can't get this running:

With this 
```bash
docker run --name 3dcitydb-o -p 1521:1521 -dit \
     -e DBUSER=usertest \
     -e ORACLE_PWD=testTest1! \
     -e ORACLE_PDB=db \
     -e SRID=25832 \
   3dcitydb/3dcitydb-ora:4.0.3
```
I get some error during DB initialization:

```
Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0

SQL> CREATE USER usertest identified by testTest1!
                                            *
ERROR at line 1:
ORA-00922: missing or invalid option


SQL>       GRANT CONNECT, RESOURCE to usertest
                                 *
ERROR at line 1:
ORA-01917: user or role 'USERTEST' does not exist


SQL>       GRANT CREATE TABLE to usertest
                            *
ERROR at line 1:
ORA-01917: user or role 'USERTEST' does not exist


SQL>       GRANT CREATE SEQUENCE to usertest
```

In any other case I can't connect to the database. 

Can you please give me a working example on how to use the 3DCityDB Docker oracle version?
This would be helpful:

1. 3DCityDB Docker Oracle build command
2. 3DCityDB oracle container, e.g.:

```
docker run --name 3dcitydb-o -p 1521:1521 -dit \
     -e DBUSER=usertest \
     -e ORACLE_PWD=testTest1! \
     -e ORACLE_PDB=db \
     -e SRID=25832 \
   3dcitydb/3dcitydb-ora:4.0.3
```

3. Oracle SQLPlus Docker connection string, e.g.:

```bash
docker run --net host -i -t --rm \
    -v ${PWD/mnt\/}:/share \
    container-registry.oracle.com/database/instantclient sqlplus \
  'usertest/testTest1!@//localhost:1521/db'
```
Thx in advance, Bruno.

**Comment by yaozhihang** [comment]
@BWibo Sorry for the my response. Below is a working example in my tests:

1. Docker Build: `docker build --tag citydb-oracle-image .`
2. Docker Run: `docker run -i -t -p 1520:1521 --name citydb-oracle-container -e DB_USER=citydb -e ORACLE_PWD=citydb -e SRID=25832 citydb-oracle-image` 

The Database connection in Importer/Exporter:
image

**Review by yaozhihang — APPROVED** [review]
@BWibo Nice fix.

**Pull request merged**
