### PR TITLE
Updated SRS package

### PR DESCRIPTION
**Pull request by FxKu**
Relevant changes:

- Added schema_name parameter to function is_db_coord_ref_sys_3d
- Introducing schema_name operator for change_schema_srid, change_column_srid (actually argument order should be changed), get_dim (Oracle)
- Removed dynamic SQL code if possible
- Renamed function arguments if there might be conflicts with column names in querys
- Added volatility categories (PosgreSQL) 

The reason, why Oracle had no schema_name support this far is because changing the system view all_sdo_geom_metadata requires DBA privileges which most roles will not have. Reading is ok, though. As a compromise only user_sdo_geom_metadata is updated if schema_name equals the CURRENT_USER which will likely be the case when working with the 3DCityDB under Oracle.

### CODE REVIEW

**Comment by clausnagel** [comment]
fixed above in 0277c78265f55258dd77bc4681c1c0ddc2b66a51

**Comment by clausnagel** [comment]
Should we really support changing the SRID in another schema in Oracle (i.e., `schema_name <> USER`)? Geometry and `user_sdo_geom_metadata` being out of sync does not sound like a good idea?!

Well, I understand that we have done so in the past in `IDX.sql.` `IDX.sql` also supports creating a spatial index in another schema, in which case no `user_sdo_geom_metadata` is created. Again, a good idea?

**Comment by FxKu** [comment]
Did some research on these system views and it seems that there is no way, that the DB synchs the metadata automatically. This is bad. Hm, we could provide a script that checks the spatial tables and updates the metadata. I could also find examples for such stuff in the web (e.g. synching Oracle with ESRI etc.).

A user could execute the script via the VACUUM button in the Importer/Exporter because it's more or less analogous to what happens in Postgres ;) The button name should have a more universal name then. Not perfect, but I think not many (if any) will work accross multiple user schemas in Oracle.

**Comment by FxKu** [comment]
Just checked the Imp/Exp code and VACUUM is only applied agains the indexes in index_table. I've mixed it up with the VACUUM_SPATIAL_COLUMNS script.

**Pull request merged**
