### PR TITLE
[WIP] check raster availability for PostGIS

### PR DESCRIPTION
**Pull request by FxKu**
Move raster parts to their own files:

- `SCHEMA_RASTER.sql`
- `DELETE_RASTER.sql`
- `ENVELOPE_RASTER.sql`

The `CREATE_DB.sql` and `CREATE_SCHEMA.sql` scripts check if PostGIS < v3 is installed or if `postgis_raster` extension exists. If one is true, raster parts will get created. It can also be created later by running `CREATE_DB_RASTER.sql` script.

fixes https://github.com/3dcitydb/importer-exporter/issues/106

### CODE REVIEW

**Comment by yaozhihang** [comment]
Hi Felix, many thanks for the MR. It seems to work for solving the issue https://github.com/3dcitydb/importer-exporter/issues/106. However, I have some concerns regarding the following points:
1. The current `DELELTE.sql`, `ENVELOPE.sql` and `SCHEMA.sql` were created from an automatic process, which will not work with this MR. For example, the `SCHEMA.sql` was directly derived from a PgModeler project. Wenn we make some changes to the database model in future releases, we have to manually move the raster parts from the `SCHEMA.sql` to the file `SCHEMA_RASTER.sql` . For `DELELTE.sql`, `ENVELOPE.sql` the workflow are similar. All these manual work would cause additional maintenance difficulties. 
2. With this PR, a 3DCityDB will per-default have no raster parts under PostGIS 3.0, since Raster-Extension is not per-default installed. But wenn the users install the Raster-Extension afterwards and want to make use of the 3DCityDB's raster features, should we provide an upgrade scrtips to add the raster parts to the 3DCityDB? It should be possible, but also causes more development and maintenance work.
3. For Oracle, the GeoRaster is a feature of Oracle-Spatial, not of Oracle Locator. That's why we've moved the 3DCityDB's raster parts to separate script files. This is necessary, because we want to make 3DCityDB to be compatible with Oracle-Locator, which has a cheaper price. For PostgreSQL the case is different, because PostgreSQL and PostGIS with Raster-Extesions are free. I think we should not cut down the 3DCityDB's raster parts per-default only due to PostGIS versions and missing Raster-Extension.

I would incline more towards the 1st option you proposed here https://github.com/3dcitydb/importer-exporter/issues/106#issuecomment-549901430. We could simply enforce 3DCityDB&PostGIS-3.0 users to install the Raster-Extension and domenent this in the 3DCityDB-Docu.

**Comment by FxKu** [comment]
Get your points. Simply enforcing the extension is easy for us, but I would aim for something else: Deprecate raster support at all.

PostGIS devs excluded raster support for a reason. It makes building PostGIS harder, images bigger and in the end only <5% of users need it. The future will be more and more CD/CI and requiring raster dependencies for using PostGIS with 3DCityDB only because of one table <0.1% care about feels odd. The Importer/Exporter has never supported it. I really see no point in keeping it.

Regarding the code generation, I would simply remove the corresponding parts from the ER models and only maintain the cut out raster parts (as SQL scripts), marked them deprecated and remove them in the next major release (or later). I would create a `CREATE_DB_RASTER.sql` script and call it from `CREATE_DB` (or `DO_NOTHING` if there is no raster) but you could then also execute it after setting up the DB. Would make our lives easier on the Oracle side, too. No more prompting for the version etc.

Would this require many changes in the Java world?

**Comment by yaozhihang** [comment]
@FxKu There is no need to change java code. 
Deprecating raster support for PostgreSQL must need reasonable reasons and discussed by 3DCityDB-partners. You are right, the importer-exporter has never supported the raster features. But how to make sure that other applications world-wide currently do not use it with 3DCityDB?

**Comment by FxKu** [comment]
I would deprecate it for Postgres **and** Oracle. Deprecate not delete - so users have the change to approach us and we don't break their infra. Sure, we should all agree on it.

**Comment by clausnagel** [comment]
I do like Felix' approach. This way, users can easily decide whether or not they want to have raster support. And they can even add raster support at a later point in time. If we add a corresponding paragraph to the documentation, users will clearly understand the implications.

What else is missing for this PR? Only adapting the mirgation scripts?

**Comment by FxKu** [comment]
Had a look on how to update the migration scripts, but then realized, that it's not possible to create a v2 or v3 DB without raster support :smiley:

I moved the inserts of raster entries into objectclass and aggregation_info tables in the SCHEMA_RASTER file as well. Don't know it would affect code generation, if entries are there, but tables aren't.

**Comment by FxKu** [comment]
@clausnagel @yaozhihang merged with master. Messed up my git log, unfortunately, but should be repaired now. Ready for another review.

**Comment by yaozhihang** [comment]
@FxKu many thanks for the update, greate work! Claus and I will do more tests and review. We are planning to merge this PR for the next major release v4.1.

**Comment by FxKu** [comment]
@yaozhihang @clausnagel if your fine with these changes, I can also provide a separate PR for the Oracle version which reflects this new behavior. Instead of asking for the Oracle Spatial version, we should simply check for the raster type availability.

**Comment by yaozhihang** [comment]
sorry Felix, as you have seen, many conflicts have been raised due to my latest commits in the master-branch. These commits are necessary for the next minor release 4.0.3. So, I have to do that. 

Yes, checking GeoRaster availability instead of providing an oracle version(spatial/locator) is a good idea. I would suggest that we first disucss the changes of this PR in the next 3DCityDB team meeting. After completing this PR, then we open a new PR for the Oracle version?

**Comment by FxKu** [comment]
Ok, ping me when you want to do the next meeting.

Would be nice to see all changes pushed through PRs with some explanation, btw.

**Comment by yaozhihang** [comment]
We'll drop the raster support for the next major version 5.0. I think this PR can be closed.

**Comment by clausnagel** [comment]
Linking #112, where we discuss to remove the raster support for v5. I think the final decision is still pending though.

Still closing this PR because if v5 will include raster support, we have to add the raster availability check to the new database scripts for v5. We won't add it to v4 anymore.

**Pull request closed without merging**
