### PR TITLE
use iterative approach for VACUUM_SPATIAL_COLUMNS

### PR DESCRIPTION
**Pull request by FxKu**
I came to like `\gexec` more :smiley: 
This would incl. all spatial columns in your 3dcitydb incl. ADEs tables.
It only works with `psql` though. Anybody using the script somewhere else?
The impexp does its own VACUUM calls, I checked.

### CODE REVIEW

**Comment by yaozhihang** [comment]
@FxKu thanks. I like the approach using the metadata view `geometry_columns` to support ADE. However, you are right, the `\gexec` is a nice feature, but only works with `psql`. Could it possible to introduce a database procedure which invokes the iterative VACUUM call?

**Comment by clausnagel** [comment]
No feedback from anyone using the current version of the script so far. So I'm fine with merging @FxKu proposal.

**Comment by FxKu** [comment]
As per [docs](https://www.postgresql.org/docs/14/sql-vacuum.html), "VACUUM cannot be executed inside a transaction block". Therefore, it cannot run within a transaction or procedure. One can also use this new query to provide the former version of the script by writing the result to a file.

**Comment by yaozhihang** [comment]
Thanks @FxKu. Good to know this from the docs. Let's merge it.

**Pull request merged**
