### PR TITLE
fixed Alpine Linux detection

### PR DESCRIPTION
**Pull request by BWibo**
This should fix the issue where the initdb script terminated when trying to detect Alpine linux base image.

### CODE REVIEW

**Comment by yaozhihang** [comment]
@BWibo thanks very much for the quick fix. I got one more small issue. When choosing `-e POSTGIS_SFCGAL=false`, the postgis sfcgal extension is still be installed in Debian base image. Could you check this?

**Comment by BWibo** [comment]
Hey there, that's not a bug, it's the current behavior of the variable. 
If POSTGIS_SFCGAL is set to any value, SFCGAL will be created. Just do net set the variable and SFCGAL won't be installed.
Maybe this is misleading, I can easily change this. What do you think?

**Comment by yaozhihang** [comment]
Yes, this is a little bit misleading.

**Comment by clausnagel** [comment]
I agree with @yaozhihang. I personally would prefer a fixed enumeration of allowed values for POSTGIS_SFCGAL such as 'true' and 'false' instead of installing the extension for any value. And since we use 'yes' and 'no' for other boolean flags in the shell scripts (e.g., whether to version-enable Oracle databases), it would be consistent to also offer these values. Thus, maybe we should have 'yes', 'true', 'false', and 'no' as allowed values?

Are other boolean flags offered by the PostgreSQL base image behaving this way?

**Comment by BWibo** [comment]
OK, the new behavior is that SFCGAL is only setup, if `POSTGIS_SFCGAL=<true|yes>`.
If the varibale is not set or set to any other value SFCGAL will not be installed.

> Are other boolean flags offered by the PostgreSQL base image behaving this way?

This is one of the variables I introduces for the PostgreSQL/PostGIS image, it's not inherited from the base image.
According to the docs (https://hub.docker.com/_/postgres) there are no other boolean flags.

**Comment by yaozhihang** [comment]
Thanks @BWibo , Nice fix.

**Comment by yaozhihang** [comment]
Since we are planning to make a release this week, this fix will be first merged into the release branch `release-v4.1`, which will be merged back to the master branch after release.

**Pull request merged**
