### PR TITLE
Fixed missing Dockerfile and script

### LINKED ISSUE #237: Missing Changelog support in docker scripts

### LINKED ISSUE #238: Missing Dockerfile in the distribution package

### PR DESCRIPTION
**Pull request by yaozhihang**
closes #237 
<s>closess #238 </s>

### CODE REVIEW

**Comment by clausnagel** [comment]
Thanks, @yaozhihang. I understand that we should have a Dockerfile in the distribution package. But I see two issues with the proposed solution:

1. We will have two Dockerfiles that we must update and keep in sync. The one at the root of the repo and the new one in `postgresql`.
2. If you just clone the repo but don't build a distribution package, you can still use the Dockerfile in `postgresql` to create an image. The resulting image is _not usable_, however, because it is built using the SQL scripts `datatype-instance.sql` and `objectclass-instance.sql` containing tokens. The tokens are only replaced when creating a distribution package.

Any idea how we could at least address issue 2?

**Comment by yaozhihang** [comment]
@BWibo do you have any idea?

**Comment by BWibo** [comment]
I'm on vacation for the next two weeks, I'll look into this when I return.

**Comment by BWibo** [comment]
OK, I found some more time to look into this. Forget my previous post.
- One option is to rework the Dockerfiles to perform the `gradle build`. That would make the Dockerfiles more complex, but allow for replacing the tokens. In general, the Dockerfile should contain a build process that will work in any situation.

**Comment by clausnagel** [comment]
@BWibo, are you sure you are checking the `v5-devel` branch for this issue?

The Dockerfile in the root folder of the `v5-devel` branch already performs a Gradle build. So, this work fine. The issue is more when the Gradle build is invoked manually or via our pipelines. Then the resulting build package of the 3DCityDB scripts does not contain a Dockerfile which could be used to create a Docker image. And this Dockerfile would not need to perform a Gradle build, because the tokens are already replaced in the build package.

**Comment by BWibo** [comment]
@clausnagel Oh your right, my bad. I was completely mistaken and indeed looking at `v4`.

So the question is if we _really_ need the `Dockerfile` in the dist archive?

One could argue that the Docker image and the distribution archive a two _different distributions_ / _distributions products_ we provide. We could document the build process for both of them or give a hint to lead users in the right direction.
I don't see that it is a necessity to be able to build the Docker image from the distribution archive. If you want to build the image, just do this as we document it (Clone the repo, Use the `Dockerfile` there to build the image, see [here](https://3dcitydb-docs.readthedocs.io/en/latest/3dcitydb/docker.html#postgresql-postgis)). We might have to slightly modify the build documentation.

If we want to have the `Dockerfile` in the dist archive, can't we just copy it there use Gradle?
I'm not a gradle expert, but a quick search brought up this:
https://docs.gradle.org/current/userguide/distribution_plugin.html#sec:distribution_contents

**Comment by clausnagel** [comment]
Thanks for re-checking, @BWibo. Yes, we can easily use Gradle to copy files. However, and that was my original point, we cannot simply copy the exising `Dockerfile` from the root folder because this wouldn't work as-is in the distribution folder. So, either we 1) dynamically adapt the existing `Dockerfile` while copying, or 2) create the `Dockerfile` for the distribution package fully automatically, or 3) have a redundant second `Dockerfile` that works with the distribution package. 

This PR proposes option 3). But, as an additional problem, this second `Dockerfile` is currently stored in the subfolder `postgresql`. If you clone the repo, change into the `postgresql` directory and build a Docker image using this `Dockerfile`, the resulting image will not be working because the SQL scripts have unresolved tokens (you can simply test it by cloning the `v5-hotfix-dockerfile` branch).

So, yes, your question is valid. Do we really need this additional `Dockerfile`? I don't think so. But @yaozhihang, maybe you want to comment on this.

**Comment by yaozhihang** [comment]
The additional `Dockerfile` is not very necessary. We could add some hints or examples in the docs, and the users can create `Dockerfile` by themselves.

**Comment by clausnagel** [comment]
Ok, thanks for your feedback, @yaozhihang. Then I would say we limit this PR to issue #237.

**Comment by BWibo** [comment]
@yaozhihang @clausnagel Sounds good to leave the additional `Dockerfile` out, if we don't have a clear use-case. I'll update the build process for the Docker distribution for `v5`.

**Comment by clausnagel** [comment]
> @yaozhihang @clausnagel Sounds good to leave the additional `Dockerfile` out, if we don't have a clear use-case. I'll update the build process for the Docker distribution for `v5`.

Just curious what you want to update? I thought the current process works fine.

**Review by clausnagel — APPROVED** [review]

**Comment by BWibo** [comment]
@clausnagel 
Sry, my previous post was a bit misleading. I don't wanna touch the build process. I want to check if the docs for the process are up-to-date.

**Pull request merged**
