### PR TITLE
Add postgres15 and postgis 3.3 support

### PR DESCRIPTION
**Pull request by BWibo**
This PR adds:

* Edge images (`edge`, `edge-alpine`) now use `postgres-15` with `postgis-3.3` as base images.
* Add `11-3.3`, `12-3.3`, `13-3.3`, `14-3.3`, `15-3.2`, `15-3.3` image variants to release imags.
* The `latest` tag will for now point at `14-3.3`. I suggest we do some testing with the `edge` images using `postgres-15` before we move the `latest` tag, that people download by default to `15-3.3`.

* Release notes [postgres-15](https://www.postgresql.org/about/news/postgresql-15-released-2526/)
* Release notes [postgis-3.3](https://postgis.net/2022/08/27/postgis-3.3.0-released/)

### ToDos:

- [x] Update Github workflows
- [x] Update documentation: See https://github.com/3dcitydb/3dcitydb-docs/pull/42
- [x] **We decided to stick to PG14 for now**: After testing, `postgres-15` and `postgis-3.3` update latest image

### CODE REVIEW

**Review by yaozhihang — COMMENTED** [review]
@BWibo should the following two code lines also be updated?
https://github.com/3dcitydb/3dcitydb/blob/master/postgresql/Dockerfile#L7
https://github.com/3dcitydb/3dcitydb/blob/master/postgresql/DockerScripts/docker-build.sh#L4

**Comment by BWibo** [comment]
Thx @yaozhihang, 
I updated to local build script with the missing versions.
I also added some options to avoid pushing to DockerHub accidentally and configure a custom repo.

Regarding: https://github.com/3dcitydb/3dcitydb/blob/master/postgresql/Dockerfile#L7

The value given here is usally overwritten by build workflows/scripts. So we do not necessarily need to maintain this.
However, it makes sence to keep it up to date.

**Comment by BWibo** [comment]
PS: Here are some images available for testing:
https://hub.docker.com/r/bwibo/3dcitydb-pg/tags

**Comment by BWibo** [comment]
I added a small fix and tested to workflows, ready to merge from myside.

**Pull request merged**
