### PR TITLE
Docker upgrades

### PR DESCRIPTION
**Pull request by BWibo**
This PR includes:

- [x] Publish images to Github Container registry in addition to Dockerhub
- [x] Rework Github workflow using [Docker metatdata action](https://github.com/marketplace/actions/docker-metadata-action):
  -  More flexibility when creating image tags
  - Set OCI standard image labels, see https://github.com/opencontainers/image-spec/blob/main/annotations.md
  - Additional images for each maior and minor release version, e.g.
    - : `16-3.4-4` references latest minor version of v4 -> `16-3.4-4.4.0`
    - : `16-3.4-4.2` references latest minor version of v4 -> `16-3.4-4.2.9`
- [x] Sunset image versions, that have reached end of life:
  - https://www.postgresql.org/support/versioning/: <= PostgreSQL v10
- [x] If possible, find a better way to set `latest` tag
- [x] Update documentation: 3dcitydb/3dcitydb-docs#48

### CODE REVIEW

**Comment by clausnagel** [comment]
Hi @BWibo, what's the status of this PR? Are you working on it?

**Comment by BWibo** [comment]
@clausnagel 
Hey, it's ready. Only thing missing is updating the docs.

**Comment by BWibo** [comment]
@clausnagel @yaozhihang @thomashkolbe 
Do you agree with sunsetting the EOL Postgres versions? I assume nobody will miss them.

**Comment by clausnagel** [comment]
> @clausnagel @yaozhihang @thomashkolbe Do you agree with sunsetting the EOL Postgres versions? I assume nobody will miss them.

Absolutely. We should not offer Docker images which might have vulnerabilities. And end-of-life versions do not receive security updates anymore.

For the same reason, we changed the system requirements in the [online documentation](https://3dcitydb-docs.readthedocs.io/en/version-2023.0/first-steps/system-requirements.html). It now says that PostgreSQL 11 or higher is required.

**Comment by BWibo** [comment]
I think we can leave out Postges 11 too. It's EOL is 9th of November 2023.

**Comment by clausnagel** [comment]
Yes, agree.

> I think we can leave out Postges 11 too. It's EOL is 9th of November 2023.

Yes, agree.

**Comment by BWibo** [comment]
@clausnagel @yaozhihang @muratkendir One more thing we should discuss. Do we have use for images build for every commit to a PR? For instance:

1. Push commit `abc1234` to the `v5-devel` branch, which feeds the PR with event number `#8` .
2. Following images are built and published on `ghcr.io`:
  - `ghcr.io/3dcitydb/3dcitydb-pg:pr-8` --> This image is build from the latest commit of the PR.
  - `ghcr.io/3dcitydb/3dcitydb-pg:pr-8-abc1234` --> This image is build for a sepcific commit.

If we want to keep the registry of the release versions clean of dev images, we could introduce e.g.  `ghcr.io/3dcitydb/3dcitydb-pg-dev`.

Every now and then, we should delete the PR images. E.g. when a PR is merged/closed.

**Comment by clausnagel** [comment]
Personally, I don't see the need for having dev images that are built from PRs and even commits inside a PR.

**Comment by thomashkolbe** [comment]
I agree.

---------------------------------------------------
Prof. Dr. Thomas H. Kolbe  -  Chair of Geoinformatics
Dept. of Aerospace and Geodesy
TUM School of Engineering and Design
Technische Universität München
Arcisstr. 21, 80333 München, Germany
Tel.: +49 89 28923888  WWW: https://www.asg.ed.tum.de/gis/


Am 04.11.2023 um 12:10 schrieb Claus Nagel ***@***.***>:

﻿

Personally, I don't see the need for having dev images that are built from PRs and even commits inside a PR.

**Pull request merged**
